version: '3'
networks:
  sakai:  
services:
  jenkins:
    build: .
    networks:
      - sakai
    volumes:
      # docker share volumes
      - /var/run/docker.sock:/var/run/docker.sock
      # jenkins share volumes (jenkinsci home, and jenkins user home)
      - /opt/jenkins_home:/opt/jenkins_home
      - /opt/jenkins:/var/jenkins_home
    ports:
      - "8080"
    environment:
      - VIRTUAL_PROTO=http
      - VIRTUAL_PORT=8080
      - JENKINS_HOME=/opt/jenkins_home
    env_file:
      # Use this file to set Oracle Credentials and all server names
      # VIRTUAL_HOST (for jenkins), SERVER_NAME_<branch> (for each test server)
      # SAKAI_DB configuration, see sample_variables.env for more
      - variables.env

  nginx:
    image: jwilder/nginx-proxy
    networks:
      - sakai
    volumes:
      # nginx volumes
      - "./certs:/etc/nginx/certs"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    ports:
      - "80:80"
      - "443:443"
