jenkins:
   build: .
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /usr/bin/docker:/usr/bin/docker
     - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
     - /var/jenkins_home:/var/jenkins_home
   ports:
     - "80:8080"
   env_file:
     - variables.env
     