version: '3'
networks:
  default:
    external:
      name: nightly_sakai
services:
  sakai:
    image: tomcat:8.0.41-jre8
    ports:
      - "8080"
      - "8025"
    volumes:
      # Sakai folders and files
      - ./tomcat/lib:/usr/local/tomcat/sakai-lib
      - ./tomcat/components:/usr/local/tomcat/components
      - ./tomcat/webapps:/usr/local/tomcat/webapps
      - ./tomcat/sakai:/usr/local/tomcat/sakai
      - ./tomcat/conf/server.xml:/usr/local/tomcat/conf/server.xml
      - ./tomcat/conf/context.xml:/usr/local/tomcat/conf/context.xml
      - ./tomcat/bin/setenv.sh:/usr/local/tomcat/bin/setenv.sh
      - ./tomcat/bin/entrypoint.sh:/usr/local/tomcat/bin/entrypoint.sh
      - ./tomcat/bin/wait-for-it.sh:/usr/local/tomcat/bin/wait-for-it.sh
    command: ["/usr/local/tomcat/bin/wait-for-it.sh", "--timeout=5", "dbmysql:3306", "--", "/bin/bash", "-c", "entrypoint.sh"]
    environment:
      - SAKAI_USER=root
      - CATALINA_OPTS_EXTRA=-Dsakai.demo=true
      - VIRTUAL_HOST=${SAKAI_SERVER_NAME}
      - VIRTUAL_PROTO=http
      - VIRTUAL_PORT=8080
      - DB_USER=${SAKAI_DB_USER}
      - DB_PASS=${SAKAI_DB_PASS}
      - DB_NAME=${SAKAI_DB_NAME}
    links:
      - dbmysql

  dbmysql:
    image: mysql:5.6.27
    environment:
      - MYSQL_ROOT_PASSWORD= 
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
      - MYSQL_USER=${SAKAI_DB_USER}
      - MYSQL_PASSWORD=${SAKAI_DB_PASS}
      - MYSQL_DATABASE=${SAKAI_DB_NAME}
    command:
      - --character-set-server=utf8
    ports:
      - "3306"
